ALTER TABLE "libro" ADD COLUMN IF NOT EXISTS "pagina_actual" INTEGER DEFAULT 0;
ALTER TABLE "libro" ADD COLUMN IF NOT EXISTS "paginas_totales" INTEGER DEFAULT 100;
ALTER TABLE "foro" ADD COLUMN IF NOT EXISTS "es_apl" BOOLEAN DEFAULT false;